[build-system]
requires = [
    "poetry-core>=1.0.0",
    "setuptools>=65.0",
    "wheel",
]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "datastew"
version = "0.1.0"
description = "Datastew is a python library for intelligent data harmonization using Large Language Model (LLM) vector embeddings."
authors = ["Tim Adams <tim.adams@scai.fraunhofer.de>", "Mehmet Can Ay <mehmet.ay@scai.fraunhofer.de>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/SCAI-BIO/datastew"
repository = "https://github.com/SCAI-BIO/datastew"
documentation = "https://github.com/SCAI-BIO/datastew#readme"
keywords = ["data-harmonization", "LLM", "embeddings", "data-steward"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[tool.poetry.urls]
homepage = "https://github.com/SCAI-BIO/datastew"
repository = "https://github.com/SCAI-BIO/datastew"
documentation = "https://github.com/SCAI-BIO/datastew#readme"
tracker = "https://github.com/SCAI-BIO/datastew/issues"

[[tool.poetry.packages]]
include = "datastew"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
matplotlib = "^3.10.7"
numpy = "^2.2.6"
openai = "^2.7.1"
openpyxl = "^3.1.5"
pandas = "^2.3.3"
plotly = "^6.4.0"
python-dateutil = "^2.9.0.post0"
python-dotenv = "^1.2.1"
pytz = "^2025.2"
seaborn = "^0.13.2"
sentence-transformers = "^5.1.2"
scikit-learn = "^1.7.2"
six = "^1.17.0"
thefuzz = "^0.22.1"
tzdata = "^2025.2"
wheel = "^0.45.1"
aiofiles = "^25.1.0"
SQLAlchemy = "^2.0.44"
scipy = "^1.15.3"
pydantic = "^2.12.4"
requests = "^2.32.5"
uuid = "^1.30"
weaviate-client = "^4.17.0"
cachetools = "^6.2.1"
ollama = "^0.6.0"
pgvector = "^0.4.1"
psycopg2-binary = "^2.9.11"
torch = "^2.9.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
pytest = "^9.0.0"
