[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "datastew"
module-root = ""

[project]
name = "datastew"
version = "0.1.0"
description = "Datastew is a python library for intelligent data harmonization using Large Language Model (LLM) vector embeddings."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10,<3.14"
authors = [
    { name = "Tim Adams", email = "tim.adams@scai.fraunhofer.de" },
    { name = "Mehmet Can Ay", email = "mehmet.ay@scai.fraunhofer.de" },
]
keywords = ["data-harmonization", "LLM", "embeddings", "data-steward"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "matplotlib>=3.10.7,<4.0.0",
    "numpy>=2.2.6,<3.0.0",
    "openai>=2.7.1,<3.0.0",
    "openpyxl>=3.1.5,<4.0.0",
    "pandas>=2.3.3,<3.0.0",
    "plotly>=6.4.0,<7.0.0",
    "python-dateutil>=2.9.0.post0,<3.0.0",
    "python-dotenv>=1.2.1,<2.0.0",
    "pytz>=2025.2,<2026.0",
    "seaborn>=0.13.2,<1.0.0",
    "sentence-transformers>=5.1.2,<6.0.0",
    "scikit-learn>=1.7.2,<2.0.0",
    "six>=1.17.0,<2.0.0",
    "thefuzz>=0.22.1,<1.0.0",
    "tzdata>=2025.2,<2026.0",
    "wheel>=0.45.1,<1.0.0",
    "aiofiles>=25.1.0,<26.0.0",
    "SQLAlchemy>=2.0.44,<3.0.0",
    "scipy>=1.15.3,<2.0.0",
    "pydantic>=2.12.4,<3.0.0",
    "requests>=2.32.5,<3.0.0",
    "uuid>=1.30,<2.0.0",
    "weaviate-client>=4.17.0,<5.0.0",
    "cachetools>=6.2.1,<7.0.0",
    "ollama>=0.6.0,<1.0.0",
    "pgvector>=0.4.1,<1.0.0",
    "psycopg2-binary>=2.9.11,<3.0.0",
    "torch>=2.9.0,<3.0.0",
]

[project.optional-dependencies]
dev = ["flake8>=7.3.0,<8.0.0", "pytest>=9.0.0,<10.0.0"]


[project.urls]
Homepage = "https://github.com/SCAI-BIO/datastew"
Repository = "https://github.com/SCAI-BIO/datastew"
Documentation = "https://github.com/SCAI-BIO/datastew#readme"
Tracker = "https://github.com/SCAI-BIO/datastew/issues"
